import("//toolchain/bcs_projects.gni")

bcs_executable("definitiondumper")
{
  metadata = { project_folder = [ "//!Runtime/Development" ] }
  include_dirs = [ ]
  sources = [
    "main.cpp",
    "definition_dumper.cpp",
    "definition_dumper.h",
    "definitiondumper-private-pch.h" ]
  libs = [ ]
  deps = [
    "//framework/platform",
    "//framework/platform:platform_entry_point",
    "//framework/templatelibrary",
    "//framework/blamlib",
    "//tags/tagframework",
    "//tags/tagdefinitions",
    "//tags/runtimedefinitions",
    "//tags/tagfileserialization",
    "//tags/blamtoozle", ]
}
