import("//toolchain/bcs_projects.gni")

bcs_library("cachefileserialization")
{
  metadata = { project_folder = [ "//!Tags" ] }
  include_dirs = [ ]
  sources = [
    "cachefileserialization-private-pch.h",
    "cachefileserialization-public-pch.h",
    "eldorado/eldorado_cache_file_header.h",
    "halo1/halo1_cache_file_header.h",
    "halo1/halo1_demo_cache_file_header.h",
    "halo1/halo1_pc32_cache_file_header.h",
    "halo1/halo1_pc64_cache_file_header.h",
    "halo2/halo2_cache_file_header.h",
    "halo2/halo2_alpha_xbox_cache_file_header.h",
    "halo2/halo2_xbox_cache_file_header.h",
    "halo2/halo2_pc32_cache_file_header.h",
    "halo2/halo2_pc64_cache_file_header.h",
    "halo3/halo3_cache_file_header.h",
    "halo3/halo3_beta_xbox360_cache_file_header.h",
    "halo3/halo3_xbox360_cache_file_header.h",
    "halo3/halo3_xboxone_cache_file_header.h",
    "halo3/halo3_pc_cache_file_header.h",
    "halo3odst/halo3odst_cache_file_header.h",
    "halo3odst/halo3odst_xbox360_cache_file_header.h",
    "halo3odst/halo3odst_pc_cache_file_header.h",
    "haloreach/haloreach_cache_file_header.h",
    "haloreach/haloreach_alpha_xbox360_cache_file_header.h",
    "haloreach/haloreach_xbox360_cache_file_header.h",
    "haloreach/haloreach_pc_cache_file_header.h",
    "halo4/halo4_cache_file_header.h",
    "halo4/halo4_xbox360_cache_file_header.h",
    "halo4/halo4_pc_cache_file_header.h",
    "haloinfinite/haloinfinite_cache_file_header.h",
    "eldorado/eldorado_cache_file_header.cpp",
    "halo1/halo1_cache_file_header.cpp",
    "halo2/halo2_cache_file_header.cpp",
    "halo3/halo3_cache_file_header.cpp",
    "halo3odst/halo3odst_cache_file_header.cpp",
    "haloreach/haloreach_cache_file_header.cpp",
    "halo4/halo4_cache_file_header.cpp",
    "haloinfinite/haloinfinite_cache_file_header.cpp",
    "base/rsa_signature.h",
    "base/file_last_modification_date.h",
    "base/network_http_request_hash.h",
    "base/rsa_signature.cpp",
    "base/file_last_modification_date.cpp",
    "base/network_http_request_hash.cpp",
    "base/cache_file_header.cpp",
    "base/cache_file_header.h",
    "base/cache_file_build_info.h" ]
  libs = [ ]
  deps = [
    "//framework/platform",
    "//framework/templatelibrary",
    "//framework/blamlib" ]
}
